/*
 * File: app/store/cultMemberStore.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.cultMemberStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.cultMember'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.cultMember',
            storeId: 'MyJsonStore',
            proxy: {
                type: 'ajax',
                url: '../receivemoney_finV3/data/cult_member.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});