/*
 * File: app/view/pnAddListMoneyWindows.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.pnAddListMoneyWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.pnAddListMoneyWindows',

    draggable: false,
    height: 416,
    width: 685,
    resizable: //true
false,
    layout: {
        type: 'border'
    },
    title: 'เพิ่มข้อมูลรับเงิน',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'pnAddListMoney',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 148,
                            margin: '10 10 10 10',
                            padding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    id: 'id',
                                    fieldLabel: 'รหัส',
                                    msgTarget: 'side',
                                    name: 'id',
                                    allowBlank: false,
                                    emptyText: 'รหัสข้อมูล',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'transaction',
                                    fieldLabel: 'ประเภทรายการ',
                                    name: 'transaction',
                                    editable: false,
                                    displayField: 'Type',
                                    store: 'depositType'
                                },
                                {
                                    xtype: 'numberfield',
                                    formBind: false,
                                    id: 'deposit',
                                    fieldLabel: 'ยอดเงิน',
                                    msgTarget: 'side',
                                    name: 'deposit',
                                    allowBlank: false,
                                    emptyText: 'จำนวนที่เงิน',
                                    regexText: 'โปรดใส่ข้อมูล จำนวนเงินที่ถอน',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tellerId',
                                    fieldLabel: 'หมายเลขกำกับ',
                                    msgTarget: 'side',
                                    name: 'tellerId',
                                    emptyText: ''
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            itemId: 'btnSave',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'บันทึก'
                        },
                        {
                            xtype: 'button',
                            id: 'btnEdit',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'แก้ไขข้อมูล'
                        },
                        {
                            xtype: 'button',
                            id: 'btnClear',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'ล้างข้อมูล'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    margins: ' 0 0 0 10',
                    region: 'north',
                    height: 164,
                    id: 'pnBankForm',
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 10,
                            id: 'bookBank',
                            margin: '0 0 0 10',
                            width: 250,
                            fieldLabel: 'ชื่อธนาคาร',
                            name: 'bookBank',
                            editable: false,
                            displayField: 'bookBank',
                            store: 'BankAccountStore'
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 50,
                            id: 'accountNo',
                            margin: '0 0 0 10',
                            width: 250,
                            fieldLabel: 'เลขที่บัญชี:',
                            name: 'accountNumber'
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 90,
                            id: 'name',
                            margin: '0 0 0 10',
                            width: 250,
                            fieldLabel: 'ชื่อบัญชี',
                            name: 'name',
                            editable: false
                        },
                        {
                            xtype: 'combobox',
                            x: 310,
                            y: 50,
                            id: 'branch',
                            margin: '0 0 0 10',
                            width: 254,
                            fieldLabel: 'สาขา',
                            name: 'branch',
                            editable: false
                        },
                        {
                            xtype: 'combobox',
                            x: 310,
                            y: 10,
                            id: 'type',
                            margin: '0 0 0 10',
                            width: 254,
                            fieldLabel: 'ประเภท',
                            name: 'type',
                            editable: false
                        },
                        {
                            xtype: 'datefield',
                            x: 310,
                            y: 90,
                            id: 'date',
                            margin: '0 0 0 10',
                            width: 254,
                            fieldLabel: 'วันที่โอน',
                            name: 'date',
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 130,
                            id: 'bookBanks5',
                            margin: '0 0 0 10',
                            width: 254,
                            fieldLabel: 'TimeStamp',
                            name: 'bookBank'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});