/*
 * File: app/view/pnAddListMoneyWindows.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.pnAddListMoneyWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.pnAddListMoneyWindows',

    draggable: false,
    height: 327,
    width: 685,
    resizable: //true
false,
    layout: {
        type: 'border'
    },
    title: 'เพิ่มข้อมูลรับเงิน',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'pnAddListMoney',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: '10 10 10 10',
                            padding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    id: 'id',
                                    fieldLabel: 'รหัส',
                                    msgTarget: 'side',
                                    name: 'id',
                                    allowBlank: false,
                                    emptyText: 'รหัสข้อมูล',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'date',
                                    fieldLabel: 'วันที่โอน',
                                    msgTarget: 'side',
                                    name: 'date',
                                    emptyText: '',
                                    editable: false
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'transaction',
                                    fieldLabel: 'ประเภทรายการ',
                                    name: 'transaction',
                                    editable: false,
                                    displayField: 'Type',
                                    store: 'depositType'
                                },
                                {
                                    xtype: 'numberfield',
                                    formBind: false,
                                    id: 'deposit',
                                    fieldLabel: 'ยอดเงิน',
                                    msgTarget: 'side',
                                    name: 'deposit',
                                    allowBlank: false,
                                    emptyText: 'จำนวนที่เงิน',
                                    regexText: 'โปรดใส่ข้อมูล จำนวนเงินที่ถอน',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'tellerId',
                                    fieldLabel: 'หมายเลขกำกับ',
                                    msgTarget: 'side',
                                    name: 'tellerId',
                                    emptyText: ''
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'bookBank',
                                    fieldLabel: 'ชื่อธนาคาร',
                                    name: 'bookBank',
                                    displayField: 'bookBank',
                                    store: 'BankAccountStore'
                                },
                                {
                                    xtype: 'numberfield',
                                    id: 'accountNumber',
                                    fieldLabel: 'เลขที่บัญชี:',
                                    name: 'accountNumber'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            itemId: 'btnSave',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'บันทึก'
                        },
                        {
                            xtype: 'button',
                            id: 'btnEdit',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'แก้ไขข้อมูล'
                        },
                        {
                            xtype: 'button',
                            id: 'btnClear',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'ล้างข้อมูล'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});