/*
 * File: app/view/wnDelete.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wnDelete', {
    extend: 'Ext.window.Window',
    alias: 'widget.wnDelete',

    height: 165,
    id: 'wnDelete',
    width: 289,
    layout: {
        type: 'absolute'
    },
    icon: 'http://www.dhl.co.th/content/dam/General%20DHL%20pictures/Icons/ImportantInfo_teaser_29x29/white_icon_teaser_1_29x29.jpg',
    iconCls: '',
    title: 'คำเตือน',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    x: 0,
                    y: 40,
                    height: 20,
                    id: 'btnYes',
                    margin: '50 0 0 50',
                    width: 70,
                    icon: 'http://anonmails.de/img/icon_ok.gif',
                    text: 'ใช่'
                },
                {
                    xtype: 'button',
                    x: 110,
                    y: 40,
                    height: 20,
                    id: 'btnNo',
                    margin: '50 0 0 50',
                    width: 70,
                    icon: 'http://www.qcm.ch/typo3conf/ext/qcm_courses/res/icons/icon_no.png',
                    text: 'ไม่'
                },
                {
                    xtype: 'label',
                    x: 100,
                    y: 40,
                    height: 20,
                    html: '',
                    width: 160,
                    text: 'คุณต้องการลบข้อมูลใช่หรือไม่'
                },
                {
                    xtype: 'image',
                    x: 30,
                    y: 20,
                    height: 50,
                    width: 50,
                    src: 'http://mblog.manager.co.th/uploads/4576/images/alert.gif'
                }
            ]
        });

        me.callParent(arguments);
    }

});